/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.ui;

import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import server.interfaces.RMIMethod;
import server.models.ModelJadwalKuliah;

/**
 *
 * @author 62853
 */
public class HalamanJadwalKuliah extends javax.swing.JFrame {

    /**
     * Creates new form HalamanJadwalKuliah
     */
    
    RMIMethod rmi;
    public HalamanJadwalKuliah() {
        try {
            initComponents();
            this.setLocationRelativeTo(null);
            rmi = (RMIMethod) Naming.lookup("rmi://localhost:8989/rmiServer");
            loadDataJadwalKuliah();
        } catch (NotBoundException ex) {
            Logger.getLogger(HalamanJadwalKuliah.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(HalamanJadwalKuliah.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(HalamanJadwalKuliah.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
        public void loadDataJadwalKuliah(){
        try {
            DefaultTableModel DTM = new DefaultTableModel();
            DTM.addColumn("ID");
            DTM.addColumn("Nama");
            DTM.addColumn("Jam");
            DTM.addColumn("Hari");
            DTM.addColumn("Kelas");
            DTM.addColumn("Semester");
            DTM.addColumn("Waktu Tambah");
            DTM.addColumn("Waktu Ubah");
            
            List<ModelJadwalKuliah> data = rmi.getDataJadwalKuliah();
            System.out.println(data.get(0).getNama());
            for (ModelJadwalKuliah modelJadwalKuliah : data) {
                DTM.addRow(new Object[]{modelJadwalKuliah.getId_praktikum(), modelJadwalKuliah.getNama(), modelJadwalKuliah.getJam(), modelJadwalKuliah.getHari(), modelJadwalKuliah.getKelas(), modelJadwalKuliah.getSemester(), modelJadwalKuliah.getCreated_at(), modelJadwalKuliah.getUpdated_at()});
                TabelJadwalKuliah.setModel(DTM);
            }
            
        } catch (RemoteException ex) {
            Logger.getLogger(HalamanJadwalKuliah.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelJadwalKuliah = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TFNama = new javax.swing.JLabel();
        TFJam = new javax.swing.JLabel();
        TFHari = new javax.swing.JLabel();
        TFKelas = new javax.swing.JLabel();
        TFSemester = new javax.swing.JLabel();
        BTNKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabelJadwalKuliah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TabelJadwalKuliah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelJadwalKuliahMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelJadwalKuliah);

        jLabel1.setText("Nama : ");

        jLabel2.setText("Jam :");

        jLabel3.setText("Hari : ");

        jLabel4.setText("Kelas : ");

        jLabel5.setText("Semester : ");

        TFNama.setText("Nama");

        TFJam.setText("Jam");

        TFHari.setText("Hari");

        TFKelas.setText("Kelas");

        TFSemester.setText("Semester");

        BTNKembali.setText("Kembali");
        BTNKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNKembali))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TFSemester, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TFNama, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFJam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TFHari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(BTNKembali))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .addComponent(TFNama)
                        .addGap(18, 18, 18)
                        .addComponent(TFJam)
                        .addGap(18, 18, 18)
                        .addComponent(TFHari)
                        .addGap(18, 18, 18)
                        .addComponent(TFKelas)
                        .addGap(18, 18, 18)
                        .addComponent(TFSemester)
                        .addGap(222, 222, 222)))
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TabelJadwalKuliahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelJadwalKuliahMouseClicked
        // TODO add your handling code here:
        int row = TabelJadwalKuliah.getSelectedRow();
        String id = TabelJadwalKuliah.getModel().getValueAt(row, 0).toString();
        String nama = TabelJadwalKuliah.getModel().getValueAt(row, 1).toString();
        String jam = TabelJadwalKuliah.getModel().getValueAt(row, 2).toString();
        String hari = TabelJadwalKuliah.getModel().getValueAt(row, 3).toString();
        String kelas = TabelJadwalKuliah.getModel().getValueAt(row, 4).toString();
        String semester = TabelJadwalKuliah.getModel().getValueAt(row, 5).toString();
        
        TFNama.setText(nama);
        TFJam.setText(jam);
        TFHari.setText(hari);
        TFKelas.setText(kelas);
        TFSemester.setText(semester);
    }//GEN-LAST:event_TabelJadwalKuliahMouseClicked

    private void BTNKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNKembaliActionPerformed
        // TODO add your handling code here:
        new HalamanUtama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanJadwalKuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanJadwalKuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanJadwalKuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanJadwalKuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanJadwalKuliah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNKembali;
    private javax.swing.JLabel TFHari;
    private javax.swing.JLabel TFJam;
    private javax.swing.JLabel TFKelas;
    private javax.swing.JLabel TFNama;
    private javax.swing.JLabel TFSemester;
    private javax.swing.JTable TabelJadwalKuliah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
